<?php

namespace Mpf\TemplateBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository {

    public function getProfile($id) {
        return $this->getManager()
                        ->createQuery(
                                'SELECT p FROM MpfTemplateBundle:User p where p.username=:usuario '
                        )->setParameter('usuario', $id)
                        ->getResult();
    }

    public function getDistrito($id, $fuero, $semana, $mes) {
        if ($fuero == 'correccional') {
            return $this->getManager()
                            ->createQuery(
                                    'SELECT f.distrito FROM MpfTemplateBundle:Turno f, MpfTemplateBundle:Juzgado j    where j.juzgado=f.correccional and j.correccional=:fiscalia  and f.semana=:sem and f.mes=:month'
                            )->setParameter('fiscalia', $id)
                            ->setParameter('sem', $semana)
                            ->setParameter('month', $mes)
                            ->getResult();
        } elseif ($fuero == 'instruccion') {
            return $this->getManager()
                            ->createQuery(
                                    'SELECT f.distrito FROM MpfTemplateBundle:Turno f , MpfTemplateBundle:Juzgado j   where j.juzgado=f.instruccion and j.instruccion=:fiscalia  and f.semana=:sem and f.mes=:month'
                            )->setParameter('fiscalia', $id)
                            ->setParameter('sem', $semana)
                            ->setParameter('month', $mes)
                            ->getResult();
        } else {
            return $this->getManager()
                            ->createQuery(
                                    'SELECT f.distrito FROM MpfTemplateBundle:Menor f ,MpfTemplateBundle:Juzgado j on where j.juzgado=f.menor  and  f.menor=:fiscalia  and f.semana=:semana'
                            )->setParameter('fiscalia', $id)
                            ->setParameter('semana', $semana)
                            ->getResult();
        }
    }

}
