<?php

namespace Mpf\TemplateBundle\Repository;

/**
 * TurnoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TurnoRepository extends \Doctrine\ORM\EntityRepository {
    
}
