<?php

namespace FormularioBundle\Repository;

/**
 * AutoridadControlPrevencionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutoridadControlPrevencionRepository extends \Doctrine\ORM\EntityRepository
{
}
