<?php

namespace FormularioBundle\Repository;

/**
 * CausaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CausaRepository extends \Doctrine\ORM\EntityRepository
{
}
