<?php

namespace FormularioBundle\Repository;

/**
 * DeclaracionAnteAduanaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeclaracionAnteAduanaRepository extends \Doctrine\ORM\EntityRepository
{
}
