<?php

namespace FormularioBundle\Repository;

/**
 * DireccionCruceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DireccionCruceRepository extends \Doctrine\ORM\EntityRepository
{
}
