<?php

namespace FormularioBundle\Repository;

/**
 * DireccionMovimientoMigratoriosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DireccionMovimientoMigratoriosRepository extends \Doctrine\ORM\EntityRepository
{
}
