<?php

namespace FormularioBundle\Repository;

/**
 * DistritoFiscalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistritoFiscalRepository extends \Doctrine\ORM\EntityRepository
{
}
