<?php

namespace FormularioBundle\Repository;

/**
 * EmpresaTransporteTerrestreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpresaTransporteTerrestreRepository extends \Doctrine\ORM\EntityRepository
{
}
