<?php

namespace FormularioBundle\Repository;

/**
 * EmpresaTransporteAereoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpresaTransporteAereoRepository extends \Doctrine\ORM\EntityRepository
{
}
