<?php

namespace FormularioBundle\Repository;

/**
 * EstadoProcesalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoProcesalRepository extends \Doctrine\ORM\EntityRepository
{
}
