<?php

namespace FormularioBundle\Repository;

/**
 * FiscaliaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FiscaliaRepository extends \Doctrine\ORM\EntityRepository
{
}
