<?php

namespace FormularioBundle\Repository;

/**
 * HechoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HechoRepository extends \Doctrine\ORM\EntityRepository
{
}
