<?php

namespace FormularioBundle\Repository;

/**
 * MercaderiasProhibidasContrabandoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MercaderiasProhibidasContrabandoRepository extends \Doctrine\ORM\EntityRepository
{
}
