<?php

namespace FormularioBundle\Repository;

/**
 * ModalidadTrasladoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModalidadTrasladoRepository extends \Doctrine\ORM\EntityRepository
{
}
