<?php

namespace FormularioBundle\Repository;

/**
 * ModoTrasladoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModoTrasladoRepository extends \Doctrine\ORM\EntityRepository
{
}
