<?php

namespace FormularioBundle\Repository;

/**
 * OcultamientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OcultamientoRepository extends \Doctrine\ORM\EntityRepository
{
}
