<?php

namespace FormularioBundle\Repository;

/**
 * OtrasCausasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OtrasCausasRepository extends \Doctrine\ORM\EntityRepository
{
}
