<?php

namespace FormularioBundle\Repository;

/**
 * RelacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelacionRepository extends \Doctrine\ORM\EntityRepository
{
}
