<?php

namespace FormularioBundle\Repository;

/**
 * TipoPersonaProcesalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoPersonaProcesalRepository extends \Doctrine\ORM\EntityRepository
{
}
