<?php

namespace FormularioBundle\Repository;

/**
 * TipoRelacionVersionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoRelacionVersionRepository extends \Doctrine\ORM\EntityRepository
{
}
