<?php

namespace FormularioBundle\Repository;

/**
 * TipoTransporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoTransporteRepository extends \Doctrine\ORM\EntityRepository
{
}
