<?php

namespace FormularioBundle\Repository;

/**
 * TipoValorTransportadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoValorTransportadoRepository extends \Doctrine\ORM\EntityRepository
{
}
