<?php

namespace FormularioBundle\Repository;

/**
 * TipoMercaderiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoMercaderiaRepository extends \Doctrine\ORM\EntityRepository
{
}
