<?php

namespace FormularioBundle\Repository;

/**
 * TipoDocumentacionFalsaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoDocumentacionFalsaRepository extends \Doctrine\ORM\EntityRepository
{
}
