<?php

namespace FormularioBundle\Repository;

/**
 * TipoVehiculoParticularRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoVehiculoParticularRepository extends \Doctrine\ORM\EntityRepository
{
}
