<?php

namespace FormularioBundle\Repository;

/**
 * TipoProcedimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoProcedimientoRepository extends \Doctrine\ORM\EntityRepository
{
}
